// 🛠 General Skills (not just coding)
export const skillsList = [
  "Public Speaking",
  "Writing & Editing",
  "Graphic Design",
  "Video Editing",
  "Photography",
  "Marketing",
  "Social Media Management",
  "Event Planning",
  "Project Management",
  "Research & Analysis",
  "Data Science",
  "Finance & Budgeting",
  "Sales & Negotiation",
  "Customer Support",
  "Teaching & Training",
  "Content Creation",
  "Copywriting",
  "Branding",
  "Product Design",
  "Strategy & Consulting",
  "Business Development",
  "Community Building",
  "Networking",
  "Language Translation",
  "Psychology & Counseling",
  "Health & Fitness Coaching",
  "Music & Performing Arts",
  "Game Design",
  "3D Modeling & Animation",
  "Architecture & Interior Design",
];

// 💪 Strengths (soft skills & personal qualities)
export const strengthsList = [
  "Leadership",
  "Teamwork",
  "Creativity",
  "Adaptability",
  "Problem Solving",
  "Critical Thinking",
  "Time Management",
  "Communication",
  "Conflict Resolution",
  "Emotional Intelligence",
  "Decision Making",
  "Negotiation",
  "Empathy",
  "Resilience",
  "Accountability",
  "Vision & Strategy",
  "Initiative",
  "Patience",
  "Persuasion",
  "Discipline",
  "Collaboration",
  "Reliability",
  "Attention to Detail",
  "Optimism",
  "Flexibility",
  "Delegation",
  "Resourcefulness",
  "Openness to Feedback",
  "Active Listening",
  "Stress Management",
];
